### PR TITLE
Segment tree class added under algorithms folder

### PR DESCRIPTION
**Pull request by krypticmouse**
Added Segment Tree Class that currently supports building ST for following query based operations:-
- sum of range
- max in range
- min in range
- xor of range
- product of range

### CODE REVIEW

**Comment by Abhijit2505** [comment]
@krypticmouse The PR is good, but we follow certain guidelines with each PR,
- We create an issue before sending a PR because after the maintainer looks into the issue, he decides if there is a certain need of something extra, for example, this PR requires the hint methods to be included in the code as well.
- Don't forget to read the README.md and go through the source code properly before contributing to any opensource repo, the reason is many important things are left out when you don't do so.

I am not closing the PR, but I encourage you to please create an issue for the same and wait till the maintainer assigns and discuss the issue with you.

**Comment by krypticmouse** [comment]
@Abhijit2505 Thank you for the advice and I've created the issue for the same.

**Comment by krypticmouse** [comment]
@Abhijit2505 I've added Hint Functions added. Please Review.

**Review by Abhijit2505 — APPROVED** [review]
First Look is Good. Manual testing will be done before putting into production.

**Review by Abhijit2505 — APPROVED** [review]
First Look is Good. Manual testing will be done before putting into production.

**Pull request merged**
