### PR TITLE
Update sort.py

### LINKED ISSUE #125: different versions of QuickSort paritioning (Lomuto partition, Hoare partition)(SWOC)
**Suggest two differerent parition method **
 The partition method implemented so far is taking the last element as the pivot point i.e Lomuto. Suggest to make two different parition and explain why Hoare performs better.

**How will this impact the quicksort already in the code**
It will not, by default we can make it either one and additionally let the user type the string 'Hoore' as a parameter if they want this paritioning to be used.

**Extra feature**
guide users to the necessary material for the difference and the importance of choosing the right parition (using help() like done in the previous ones)

### PR DESCRIPTION
**Pull request by dejokz**
Hoare partition has been added.

### CODE REVIEW

**Comment by Abhijit2505** [comment]
Please add all the partitions at the same time. Don't push one by one. That just increases the complexity.

**Comment by dejokz** [comment]
a new commit with the updated code which is bug free has been added. 
-------
fixes made:
1)partition wasn't returning the index
2)quicksort_hoare wasn't recursively called.

**Comment by dejokz** [comment]
> Please add all the partitions at the same time. Don't push one by one. That just increases the complexity.

do you mean using threads??

**Comment by Abhijit2505** [comment]
> > Please add all the partitions at the same time. Don't push one by one. That just increases the complexity.
> 
> do you mean using threads??

I mean to say, if there are any other partition methods as well for the Quicksort, then please add them too in the same PR, if you don't want to add them let me know, I will merge it.

**Review by Abhijit2505 — APPROVED** [review]

**Comment by dejokz** [comment]
> I mean to say, if there are any other partition methods as well for the Quicksort, then please add them too in the same PR, if you don't want to add them let me know, I will merge it.

There is [multi-pivot](https://en.wikipedia.org/wiki/Quicksort#Multi-pivot_quicksort) partitioning. But the main ones are the hoare and lumoto which has been added.

If multi-pivot partitioning needs to be implemented I can. Assign the task to me and I'll get working on it.

**Comment by Abhijit2505** [comment]
> > I mean to say, if there are any other partition methods as well for the Quicksort, then please add them too in the same PR, if you don't want to add them let me know, I will merge it.
> 
> There is [multi-pivot](https://en.wikipedia.org/wiki/Quicksort#Multi-pivot_quicksort) partitioning. But the main ones are the hoare and lumoto which has been added.
> 
> If multi-pivot partitioning needs to be implemented I can. Assign the task to me and I'll get working on it.

No it's alright if the main pivots are added. Merging it.

**Pull request merged**
