### PR TITLE
Update algorithm.py

### PR DESCRIPTION
**Pull request by mohitmanwani02**
Added Quick Sort Algorithm.

### CODE REVIEW

**Review by Abhijit2505 — APPROVED** [review]
Not Good

**Comment by Abhijit2505** [comment]
@all-contributor add @mohitmanwani02 for code

**Comment by Abhijit2505** [comment]
There was a mistake with your PR, you have made a PR to one of the branches instead of the master branch. Anyway, that's all right.

**Review by Abhijit2505 — COMMENTED** [review]
It's spam

**Comment by nihilistdbanana** [comment]
Hi Abhijit, I just noticed that this algorithm has been merged into the master branch and is not correct. Can I correct it?

**Pull request merged**
