### PR TITLE
SWOC

### PR DESCRIPTION
**Pull request by fomalhauting**
Issue #131

### CODE REVIEW

**Comment by Abhijit2505** [comment]
Please add the hint methods as well.

**Comment by fomalhauting** [comment]
> Please add the hint methods as well.

Hey, sorry I don't know that, could you help me with that?

**Comment by Abhijit2505** [comment]
> > Please add the hint methods as well.
> 
> Hey, sorry I don't know that, could you help me with that?

Sure,
Follow these steps,
- Check the source code on the repo
- Check our documentation site

**Comment by fomalhauting** [comment]
> > > Please add the hint methods as well.
> > 
> > 
> > Hey, sorry I don't know that, could you help me with that?
> 
> Sure,
> Follow these steps,
> 
> * Check the source code on the repo
> * Check our documentation site

I followed this, I'm not sure I got it right, please have a look, thank you.

**Comment by fomalhauting** [comment]
@Abhijit2505 Can you take a look at this?

**Comment by fomalhauting** [comment]
@Abhijit2505 Can you take a look, thank you.

**Review by Abhijit2505 — CHANGES_REQUESTED** [review]
Please add code according to the repo standards.

**Pull request closed without merging**
